### ISSUE TITLE
Gib Bread Owner Rank

### ISSUE THREAD

**Issue by cs6413110** [cs6413110/Pixel-Tanks#258] opened 2024-12-09 19:42 UTC
Thumbs Up = Yes
Thumbs Down = No, it's called "owner" for a reason
Rocket = After he finished the last dag-nabbit item
Eyes = No, because we'd watch him burn the game down with admin abuse

**Comment by BreadSpammer** [comment] 2024-12-09 19:44
bRO garunteed owner rank???? sign meup

**Comment by 3foenation** [comment] 2024-12-09 19:45
lol

**Comment by 3foenation** [comment] 2024-12-09 19:45
just fix bread

**Comment by BreadSpammer** [comment] 2024-12-09 19:54
so like last item is mine, right?

**Comment by BreadSpammer** [comment] 2024-12-09 19:56
should be breadable

**Comment by cs6413110** [comment] 2024-12-09 20:29
uh no? we still need to decide/vote?

**Comment by BreadSpammer** [comment] 2024-12-09 20:32
um ok ill come up with a gud idea, bc mine jst overlaps with spike and airstrike too much.

**Comment by BreadSpammer** [comment] 2024-12-09 21:43
New item: leech

Item type: damage/healing
Item cooldown: 30 seconds

To use the item, you just hover over someone/thing with your mouse, and use it. On use, you will tether to whatever you chose whiting a 5 block radius, and will start leeching health from it.

If you leeched a player, it will deal 15 damage a second for 10 seconds, and heal you for 2/3 the damage, as long as you keep your target within the 5 blocks radius.

If you leeched a block, or a teamate, the opposite happens. You heal 15 health per second for 10 seconds, and they take 2/3 of that, unless they move further than 5 blocks of you.

The tether won't break instantly when moving away. It will take 1 second of stressing the tether to break it, so it's not useless.

This item has mutliple uses. It can be used as a worse version of tape in a pinch, and can also be used to get extra chip damage on your opponent. Using this item offensively takes huge skill, because you need to KEEP them near you in order for the full 10 seconds to run its course. If you let them, your opponent could just boost away, and make your item a waste.

This item also doesn't replace Glu for 1 reason. You can't flat with leech. Because you need to be near your target, even if you hit a block, you must stay near that block, no matter what. If someone chases you off the block, you lose that healing.

So this item is high skill, has no flatting potential, lets good players run more useful items than just dynamite, has good counterplay to make it balanced, and fills the final slot in the inventory.

**Comment by 3foenation** [comment] 2024-12-10 14:10
why not just leech tank

when you activate you get 10 seconds of leeching from the damage you deal and each hit you get 10% of the damage delt 30 second cooldown

**Comment by 3foe** [comment] 2024-12-10 14:16
not really a u decision bcuz owner rank belongs to me too. you need to talk to me before we make any hasty decisions.

**Comment by 3foe** [comment] 2024-12-10 14:18
LK voted twice so its 3-4. against bread

**Comment by BreadSpammer** [comment] 2024-12-10 14:27
bruh what happened to the vote bruh. it was 3-0, then 3-4 brh. why dont u guys want me to have owner? i made like 30% of game :(

**Comment by 3foe** [comment] 2024-12-10 14:32
exactly

**Comment by 3foe** [comment] 2024-12-10 14:33
that 30 precent is admin abuse. look at ur issues >XD

**Comment by cs6413110** [comment] 2024-12-10 15:47
> bruh what happened to the vote bruh. it was 3-0, then 3-4 brh. why dont u guys want me to have owner? i made like 30% of game :(

They saw the leech item.

Also 3%, not 30%.

**Comment by BreadSpammer** [comment] 2024-12-10 15:48
not 3% lol

**Comment by 3foe** [comment] 2024-12-10 16:01
> entire crate opening system- that's like low-level coding
 90% of ideas- that's me not you
 all textures in game- that's a minu,s not a plus
 item textures0 again a minus not a plus
 all gud death effects- all of them pirated for another video game
 majority of cosmetics- also a minus ( plus jonas did that)
 resizing menus - it took 7 years
 keybinds - ok 
most beta singleplayer levels etc - um ok 

even with all of that that doesn't deserve owner rank. maybe you help more than anyone else here idc, ur not getting owner. idc if u have coded more than Aaron you don't get owner rank, that's why I didn't push aaron to give it to me on github bcuz owners are owners, I'm not an owner, aaron is the owner. I will use my "owner" position to veto though. aaron is the true owner and nobody else is.

**Comment by BreadSpammer** [comment] 2024-12-10 16:04
you dont even have owner lol.

**Comment by BreadSpammer** [comment] 2024-12-10 18:26
Evan and lk are in my favor, so 4-3 I win

**Comment by BreadSpammer** [comment] 2024-12-10 18:26
Evan and lk are in my favor, so 4-3 I win

**Comment by cs6413110** [comment] 2024-12-10 18:38
Nah veto until item

**Comment by 3foe** [comment] 2024-12-10 18:59
> you dont even have owner lol.

in the contract that I am holding arron to I hold owner rank.

**Comment by 3foe** [comment] 2024-12-10 18:59
its a complete veto. like no chance

**Comment by BreadSpammer** [comment] 2024-12-11 13:53
> Nah veto until item

that's like how this works lol

**Comment by BreadSpammer** [comment] 2024-12-11 13:53
when item done, owner :)

**Comment by BreadSpammer** [comment] 2024-12-11 15:11
need this issue to spam items

**Comment by BreadSpammer** [comment] 2024-12-11 15:21
Saw Blade

creates a spinning saw blade that attaches to your tank. the saw blade will spin around your tank in a clockwise circle. any tanks that walk into it will take 50 damage, and can hit as many times as you can make them hit it. the saw lasts 5 seconds, and has a 25 second cooldown.

why gud item:
- 0 flatting potential
- alternative to dynamite
- synergies with warrior & stealth for extra damage when up close
- doesn't work with insta
- counters builder (halp)
- good in team fights

@cs6413110 evan, lostking, @DarkMemeGod411 VOTE
👍 = add
👎 = ew no

**Comment by BreadSpammer** [comment] 2024-12-11 15:28
Repair Circle

causes a 2x2 area to become a healing zone. it heals 25 hp per second for 10 seconds

why gud item:

VOTE
👍 = sure ig, replace crut
👎 = ew no lol

**Comment by cs6413110** [comment] 2024-12-11 16:41
Literally just add old mines back, but instead of placing as a block, making it spawn one under you after 1, 3, and 5 seconds.

**Comment by cs6413110** [comment] 2024-12-11 16:42
We can just yoink the old images so it's Infinity% breadable, and I can just code it.

**Comment by DarkMemeGod411** [comment] 2024-12-11 16:46
those images were deleted years ago, but i agree, just add the old mines

**Comment by 3foe** [comment] 2024-12-11 17:14
wiat owner rank as in full auth on the game or github owner?

**Comment by 3foe** [comment] 2024-12-11 17:14
I just made that connection lol

**Comment by DarkMemeGod411** [comment] 2024-12-11 17:22
in game

**Comment by BreadSpammer** [comment] 2024-12-11 17:31
> Literally just add old mines back, but instead of placing as a block, making it spawn one under you after 1, 3, and 5 seconds.

like ig, but its too similar to airstrike and mine

**Comment by BreadSpammer** [comment] 2024-12-11 17:39
Mine: 30 second cooldown

places a mine under you that is half a block in size. the mine will set up for 3 seconds, after which, it will be explodable, and near invisible (2-5% opacity). the mine does 200 damage when stepped on, and has a few other properties:

if it's boosted over, the mine will explode
teamates/yourself can see the mine, and wont trigger it if you step on it.

**Comment by BreadSpammer** [comment] 2024-12-11 19:51
^ ^ ^ mine is super hard to hit, because u have to preswade someone to step on it. with insta, you jsut fine and watch it go. also airstrike, so shut and upvote. also if it did 100 damage, why wouldnt u just use dynamite? we also already tried low cooldown mine... it waas so much pain

**Comment by BreadSpammer** [comment] 2024-12-12 17:28
I still get my owner once item done right? (4-3)

**Comment by 3foe** [comment] 2024-12-12 17:56
Here are some thoughtful Harkness discussion questions for Unit 5 of AP US History, which typically covers the period from 1844 to 1877, including topics such as Manifest Destiny, the Civil War, and Reconstruction:


1. Manifest Destiny and Westward Expansion

• How did the concept of Manifest Destiny shape U.S. foreign and domestic policies during the 1840s?

• To what extent did westward expansion exacerbate tensions between the North and South?

• Was the Mexican-American War (1846-1848) justified from both an ethical and a strategic perspective?


2. Sectionalism and the Causes of the Civil War

• How did differing economic systems in the North and South contribute to the growing sectional divide?

• To what extent were compromises like the Missouri Compromise, the Compromise of 1850, and the Kansas-Nebraska Act successful in addressing sectional tensions?

• Was the Civil War inevitable by the 1850s? Why or why not?


3. Abolitionism and Social Reform Movements

• How did abolitionist movements and literature (e.g., Uncle Tom’s Cabin) influence public opinion in the North and South?

• How did women’s rights advocates connect their movement to abolitionism?

• To what degree did religious and moral arguments shape the national debate over slavery?


4. Civil War Strategy and Leadership

• What role did leadership (Lincoln, Davis, Grant, Lee, etc.) play in determining the outcome of the Civil War?

• How did the Union’s advantages in population, industry, and infrastructure shape the course of the war?

• How did the Civil War transform the role of the federal government?


5. Emancipation and the Role of African Americans

• How did the Emancipation Proclamation change the goals of the Civil War?

• What role did African American soldiers and civilians play in achieving Union victory?

• To what extent did the Civil War lay the groundwork for the Civil Rights Movement?


6. Reconstruction

• To what extent was Reconstruction a success or a failure in achieving its goals?

• How did the passage of the 13th, 14th, and 15th Amendments shape the political and social landscape of the United States?

• What factors led to the rise of groups like the Ku Klux Klan, and how did they influence the outcomes of Reconstruction?


7. Legacies of the Era

• How did debates over states’ rights during this period shape American political culture in the decades that followed?

• In what ways did the Civil War and Reconstruction redefine the meaning of freedom in America?

• How do the events of this period continue to influence American society today?


These questions are open-ended and designed to provoke discussion and critical thinking. Let me know if you’d like more tailored questions or additional context for any specific topic!



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cs6413110** [comment] 2024-12-12 19:39
aaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by cs6413110** [comment] 2024-12-12 19:39
Ok ig

**Comment by BreadSpammer** [comment] 2024-12-12 19:41
YAYYAYAYAYYSYASYSYYASYSYSSASI AIY ISAOIFH FOAHF JN NUGUSGSS  🤤 OJFIOAHIUSY UIH INONOMGOAE AYWAS AWOnerERRER RO NENRORN EO NROERN OROOOWWWNNNEEERRRR YAS AS ASK SLK :LASK:LKD:LKG:LKG: JLESAASSSGGOOOOOHOHOHOW IAUDO IUAOWIDOISNDASDKMASDK O 🍞 🍞  OMG lAWD IWOAJD PO!) J (_JE!

closing...

**Closed by BreadSpammer** 2024-12-12 19:41 UTC
